#!/usr/bin/env bash

# Title:         ssic: Svelte SVG Icon creater
# Description:   Create SVG icons for Svelte
# Author:        Shinichi Okada <okada.shin@gmail.com>
# Date:          2022-02-10
# Update:        2022-10-10

set -eu
VERSION="2.0.0"
SCRIPT_NAME=$(basename "$0")

# Set variables

SCRIPTDIR=$(pwd)
# echo "Your current dir is: ${SCRIPTDIR}"

# Keep readlinkf function
readlinkf() {
    [ "${1:-}" ] || return 1
    max_symlinks=40
    CDPATH='' # to avoid changing to an unexpected directory

    target=$1
    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
    [ -d "${target:-/}" ] && target="$target/"

    cd -P . 2>/dev/null || return 1
    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
        if [ ! "$target" = "${target%/*}" ]; then
            case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
            esac
            target=${target##*/}
        fi

        if [ ! -L "$target" ]; then
            target="${PWD%/}${target:+/}${target}"
            printf '%s\n' "${target:-/}"
            return 0
        fi
        link=$(ls -dl -- "$target" 2>/dev/null) || break
        target=${link#*" $target -> "}
    done
    return 1
}

self=$(readlinkf "$0")
script_dir=${self%/*}
# For Debian APT remove line 7 to 38 and use the following line to
# define the script_dir
# script_dir="/usr/share/shellscript_template"

# Import files
# shellcheck disable=SC1091
{
    . "${script_dir}/lib/bash_helpers.sh"
    . "${script_dir}/lib/getoptions.sh"
    . "${script_dir}/lib/main_definition.sh"
    . "${script_dir}/lib/utils.sh"
    # icons definitions
    . "${script_dir}/lib/definitions/ant/ant_definition.sh"
    . "${script_dir}/lib/definitions/awesome/awesome_definition.sh"
    . "${script_dir}/lib/definitions/bootstrap/bootstrap_definition.sh"
    . "${script_dir}/lib/definitions/box/boxicons_definition.sh"
    . "${script_dir}/lib/definitions/cssgg/css_definition.sh"
    . "${script_dir}/lib/definitions/coreui/coreui_definition.sh"
    . "${script_dir}/lib/definitions/circle/circle_flags_definition.sh"
    . "${script_dir}/lib/definitions/crypto/crypto_definition.sh"
    . "${script_dir}/lib/definitions/evil/evil_definition.sh"
    . "${script_dir}/lib/definitions/feather/feather_definition.sh"
    . "${script_dir}/lib/definitions/file/file_definition.sh"
    . "${script_dir}/lib/definitions/flag/flagicons_definition.sh"
    . "${script_dir}/lib/definitions/flags/flags_definition.sh"
    . "${script_dir}/lib/definitions/flowbite/flowbite_definition.sh"
    . "${script_dir}/lib/definitions/google/google_material_design_definition.sh"
    . "${script_dir}/lib/definitions/hero/hero_definition.sh"
    . "${script_dir}/lib/definitions/ion/ion_definition.sh"
    . "${script_dir}/lib/definitions/lucide/lucide_definition.sh"
    . "${script_dir}/lib/definitions/material/material_definition.sh"
    . "${script_dir}/lib/definitions/oct/oct_definition.sh"
    . "${script_dir}/lib/definitions/radix/radix_definition.sh"
    . "${script_dir}/lib/definitions/remix/remix_definition.sh"
    . "${script_dir}/lib/definitions/simple/simple_definition.sh"
    . "${script_dir}/lib/definitions/supertiny/supertiny_definition.sh"
    . "${script_dir}/lib/definitions/tabler/tabler_definition.sh"
    . "${script_dir}/lib/definitions/teeny/teeny_definition.sh"
    . "${script_dir}/lib/definitions/twemoji/twemoji_definition.sh"
    . "${script_dir}/lib/definitions/weather/weather_definition.sh"
}

# Keep it. You need this for main parser.
eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

# CHECK ENVIRONMENT
# If you need to check OS uncomment this
# if [ "$(uname)" = "Linux" ]; then
#     echo "Your OS is Linux."
# elif [ "$(uname)" = "Darwin" ]; then
#     echo "Your OS is mac."
# fi

# If you are using Bash, check Bash version
check_bash 5

check_cmd rename
# Check if sed is GNU
is_gnu_sed || echo 'Please install GNU sed'

# Add more commands.
# Don't forget to add your command in lib/main_definition.sh
if [ $# -gt 0 ]; then
    cmd=$1
    shift
    case $cmd in
    ant)
        eval "$(getoptions parser_definition_ant parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/ant/ant-v0-5.sh"
        fn_ant "$@"
        ;;
    ant-next)
        eval "$(getoptions parser_definition_ant parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/ant/ant-v2-next.sh"
        fn_ant "$@"
        ;;
    awesome)
        eval "$(getoptions parser_definition_awesome parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/awesome/awesome-v1.sh"
        fn_awesome "$@"
        ;;
    awesome-next)
        eval "$(getoptions parser_definition_awesome parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/awesome/awesome-v2-next.sh"
        fn_awesome "$@"
        ;;
    bootstrap)
        eval "$(getoptions parser_definition_bootstrap parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/bootstrap/bootstrap-v0-6.sh"
        fn_bootstrap "$@"
        ;;
    box)
        eval "$(getoptions parser_definition_boxicons parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/box/boxicons-v0-3.sh"
        fn_boxicons "$@"
        ;;
    circle-flags)
        eval "$(getoptions parser_definition_circle_flags parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/circle-flags/circle_flags-v0-7.sh"
        fn_circle_flags "$@"
        ;;
    coreui)
        eval "$(getoptions parser_definition_coreui parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/coreui/coreui-v0-3.sh"
        fn_coreui "$@"
        ;;
    crypto)
        eval "$(getoptions parser_definition_crypto parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/crypto/crypto-v0-7.sh"
        fn_crypto "$@"
        ;;
    css)
        eval "$(getoptions parser_definition_css parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/css/css-v0-3.sh"
        fn_css "$@"
        ;;
    evil)
        eval "$(getoptions parser_definition_evil parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/evil/evil-v0-3.sh"
        fn_evil "$@"
        ;;
    feather)
        eval "$(getoptions parser_definition_feather parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/feather/feather-v1.sh"
        fn_feather "$@"
        ;;
    file)
        eval "$(getoptions parser_definition_file parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/fileicons/file-v0-8.sh"
        fn_file "$@"
        ;;
    flags)
        eval "$(getoptions parser_definition_flags parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flags/flags-v0-6.sh"
        fn_flag "$@"
        ;;
    flags-next)
        eval "$(getoptions parser_definition_flags parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flags/flags-v2.sh"
        fn_flag "$@"
        ;;
    flag-icons)
        eval "$(getoptions parser_definition_flagicons parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flag-icons/flag-icons-v0-7.sh"
        fn_flagicons "$@"
        ;;
    flag-icons-next)
        eval "$(getoptions parser_definition_flagicons parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flag-icons/flag-icons-v2.sh"
        fn_flagicons "$@"
        ;;
    flowbite)
        eval "$(getoptions parser_definition_flowbite parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flowbite/flowbite-v1.sh"
        fn_flowbite "$@"
        ;;
    flowbite-next)
        eval "$(getoptions parser_definition_flowbite parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flowbite/flowbite-v2-next.sh"
        fn_flowbite "$@"
        ;;
    google-material-design)
        eval "$(getoptions parser_definition_google_material_design parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/google-material/google-material-v0-8.sh"
        fn_google_material_design "$@"
        ;;
    heros)
        eval "$(getoptions parser_definition_hero parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/heros/heros-v6.sh"
        fn_hero "$@"
        ;;
    heros-next)
        eval "$(getoptions parser_definition_hero parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/heros/next/heros-next-v2.sh"
        fn_hero_next "$@"
        ;;
    heros2)
        eval "$(getoptions parser_definition_hero parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/heros2/heros2-v1.sh"
        fn_hero2 "$@"
        ;;
    heros2-next)
        eval "$(getoptions parser_definition_hero parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/heros2/next/heros2-v2-next.sh"
        fn_hero2 "$@"
        ;;
    ion)
        eval "$(getoptions parser_definition_ion parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/ion/ion-v0-7.sh"
        fn_ion "$@"
        ;;
    ion-next)
        eval "$(getoptions parser_definition_ion parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/ion/next/ion-v2.sh"
        fn_ion "$@"
        ;;
    lucide)
        eval "$(getoptions parser_definition_lucide parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/lucide/lucide-v0-8.sh"
        fn_lucide "$@"
        ;;
    lucide-next)
        eval "$(getoptions parser_definition_lucide parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/lucide/lucide-v2-next.sh"
        fn_lucide "$@"
        ;;
    material)
        eval "$(getoptions parser_definition_material parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/material/material-design-v0-8.sh"
        fn_material "$@"
        ;;
    oct)
        eval "$(getoptions parser_definition_oct parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/oct/oct-v0-6.sh"
        fn_oct "$@"
        ;;
    radix)
        eval "$(getoptions parser_definition_radix parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/radix/radix-v0-6.sh"
        fn_radix "$@"
        ;;
    radix-next)
        eval "$(getoptions parser_definition_radix parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/radix/radix-v2.sh"
        fn_radix "$@"
        ;;
    remix)
        eval "$(getoptions parser_definition_remix parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/remix/remix-v0-6.sh"
        fn_remix "$@"
        ;;
    
    remix-next)
        eval "$(getoptions parser_definition_remix parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/remix/remix-v2.sh"
        fn_remix "$@"
        ;;
    simple)
        eval "$(getoptions parser_definition_simple parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/simple/simple-v0-9.sh"
        fn_simple "$@"
        ;;
    supertiny)
        eval "$(getoptions parser_definition_supertiny parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/supertiny/supertiny-v0-3.sh"
        fn_supertiny "$@"
        ;;
    supertiny-next)
        eval "$(getoptions parser_definition_supertiny parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/supertiny/supertiny-v2-next.sh"
        fn_supertiny "$@"
        ;;
    tabler)
        eval "$(getoptions parser_definition_tabler parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/tabler/tabler-v0-6.sh"
        fn_tabler "$@"
        ;;
    # 
    # Use tabler-outline-next instead. It is too big to add both icons
    # 
    # tabler-next)
    #     eval "$(getoptions parser_definition_tabler parse "$0")"
    #     parse "$@"
    #     eval "set -- $REST"
    #     # shellcheck disable=SC1091
    #     . "${script_dir}/src/tabler/tabler-v2.sh"
    #     fn_tabler_next "$@"
    #     ;;
    tabler-outline-next)
        eval "$(getoptions parser_definition_tabler parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/tabler/tabler-outline-v2.sh"
        fn_tabler_outline "$@"
        ;;
    # Too big to add filled icons
    # tabler-filled-next)
    #     eval "$(getoptions parser_definition_tabler parse "$0")"
    #     parse "$@"
    #     eval "set -- $REST"
    #     # shellcheck disable=SC1091
    #     . "${script_dir}/src/tabler/tabler-filled-v2.sh"
    #     fn_tabler_filled "$@"
    #     ;;
    teeny)
        eval "$(getoptions parser_definition_teeny parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/teeny/teeny-v0-9.sh"
        fn_teeny "$@"
        ;;
    twemoji)
        eval "$(getoptions parser_definition_twemoji parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/twemoji/twemoji-v0-6.sh"
        fn_twemoji "$@"
        ;;
    weather)
        eval "$(getoptions parser_definition_weather parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/weather/weather-v0-5.sh"
        fn_weather "$@"
        ;;
    # more lines
    --) ;; # no subcommand, arguments only
    esac
fi
