#!/usr/bin/env bash

# Title:         ssic: Svelte SVG Icon creater
# Description:   Create SVG icons for Svelte
# Author:        Shinichi Okada <okada.shin@gmail.com>
# Date:          2022-02-10
# Update:        2022-08-25

set -eu
VERSION="1.10.0"
SCRIPT_NAME=$(basename "$0")

# Set variables

SCRIPTDIR=$(pwd)
# echo "Your current dir is: ${SCRIPTDIR}"

# Keep readlinkf function
readlinkf() {
    [ "${1:-}" ] || return 1
    max_symlinks=40
    CDPATH='' # to avoid changing to an unexpected directory

    target=$1
    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
    [ -d "${target:-/}" ] && target="$target/"

    cd -P . 2>/dev/null || return 1
    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
        if [ ! "$target" = "${target%/*}" ]; then
            case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
            esac
            target=${target##*/}
        fi

        if [ ! -L "$target" ]; then
            target="${PWD%/}${target:+/}${target}"
            printf '%s\n' "${target:-/}"
            return 0
        fi
        link=$(ls -dl -- "$target" 2>/dev/null) || break
        target=${link#*" $target -> "}
    done
    return 1
}

self=$(readlinkf "$0")
script_dir=${self%/*}
# For Debian APT remove line 7 to 38 and use the following line to
# define the script_dir
# script_dir="/usr/share/shellscript_template"

# Import files
# shellcheck disable=SC1091
{
    . "${script_dir}/lib/awesome_definition.sh"
    . "${script_dir}/lib/bash_helpers.sh"
    . "${script_dir}/lib/bootstrap_definition.sh"
    . "${script_dir}/lib/circle_flags_definition.sh"
    . "${script_dir}/lib/crypto_definition.sh"
    . "${script_dir}/lib/feather_definition.sh"
    . "${script_dir}/lib/file_definition.sh"
    . "${script_dir}/lib/flag_definition.sh"
    . "${script_dir}/lib/flagicons_definition.sh"
    . "${script_dir}/lib/getoptions.sh"
    . "${script_dir}/lib/google_material_design_definition.sh"
    . "${script_dir}/lib/hero_definition.sh"
    . "${script_dir}/lib/ion_definition.sh"
    . "${script_dir}/lib/lucide_definition.sh"
    . "${script_dir}/lib/main_definition.sh"
    . "${script_dir}/lib/material_definition.sh"
    . "${script_dir}/lib/oct_definition.sh"
    . "${script_dir}/lib/radix_definition.sh"
    . "${script_dir}/lib/remix_definition.sh"
    . "${script_dir}/lib/simple_definition.sh"
    . "${script_dir}/lib/tabler_definition.sh"
    . "${script_dir}/lib/teeny_definition.sh"
    . "${script_dir}/lib/twemoji_definition.sh"
    . "${script_dir}/lib/utils.sh"
    . "${script_dir}/lib/weather_definition.sh"
}

# Keep it. You need this for main parser.
eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

# CHECK ENVIRONMENT
# If you need to check OS uncomment this
# if [ "$(uname)" = "Linux" ]; then
#     echo "Your OS is Linux."
# elif [ "$(uname)" = "Darwin" ]; then
#     echo "Your OS is mac."
# fi

# If you are using Bash, check Bash version
check_bash 5

# Check if sed is GNU
is_gnu_sed || echo 'Please install GNU sed'

# Add more commands.
# Don't forget to add your command in lib/main_definition.sh
if [ $# -gt 0 ]; then
    cmd=$1
    shift
    case $cmd in
    awesome)
        eval "$(getoptions parser_definition_awesome parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/awesome.sh"
        fn_awesome "$@"
        ;;
    bootstrap)
        eval "$(getoptions parser_definition_bootstrap parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/bootstrap.sh"
        fn_bootstrap "$@"
        ;;
    circle-flags)
        eval "$(getoptions parser_definition_circle_flags parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/circle_flags.sh"
        fn_circle_flags "$@"
        ;;
    crypto)
        eval "$(getoptions parser_definition_crypto parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/crypto.sh"
        fn_crypto "$@"
        ;;
    feather)
        eval "$(getoptions parser_definition_feather parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/feather.sh"
        fn_feather "$@"
        ;;
    file)
        eval "$(getoptions parser_definition_file parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/file.sh"
        fn_file "$@"
        ;;
    flag)
        eval "$(getoptions parser_definition_flag parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flag.sh"
        fn_flag "$@"
        ;;
    flag-icons)
        eval "$(getoptions parser_definition_flagicons parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/flag-icons.sh"
        fn_flagicons "$@"
        ;;
    google-material-design)
        eval "$(getoptions parser_definition_google_material_design parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/google_material_design.sh"
        fn_google_material_design "$@"
        ;;
    hero)
        eval "$(getoptions parser_definition_hero parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/hero.sh"
        fn_hero "$@"
        ;;
    hero2)
        eval "$(getoptions parser_definition_hero parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/hero2.sh"
        fn_hero2 "$@"
        ;;
    ion)
        eval "$(getoptions parser_definition_ion parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/ion.sh"
        fn_ion "$@"
        ;;
    lucide)
        eval "$(getoptions parser_definition_lucide parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/lucide.sh"
        fn_lucide "$@"
        ;;
    material)
        eval "$(getoptions parser_definition_material parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/material_design.sh"
        fn_material "$@"
        ;;
    oct)
        eval "$(getoptions parser_definition_oct parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/oct.sh"
        fn_oct "$@"
        ;;
    radix)
        eval "$(getoptions parser_definition_radix parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/radix.sh"
        fn_radix "$@"
        ;;
    remix)
        eval "$(getoptions parser_definition_remix parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/remix.sh"
        fn_remix "$@"
        ;;
    simple)
        eval "$(getoptions parser_definition_simple parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/simple.sh"
        fn_simple "$@"
        ;;
    tabler)
        eval "$(getoptions parser_definition_tabler parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/tabler.sh"
        fn_tabler "$@"
        ;;
    teeny)
        eval "$(getoptions parser_definition_teeny parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/teeny.sh"
        fn_teeny "$@"
        ;;
    twemoji)
        eval "$(getoptions parser_definition_twemoji parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/twemoji.sh"
        fn_twemoji "$@"
        ;;
    weather)
        eval "$(getoptions parser_definition_weather parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/weather.sh"
        fn_weather "$@"
        ;;
    # more lines
    --) ;; # no subcommand, arguments only
    esac
fi
